FROM node:14
WORKDIR /
COPY src /opt/neurodiversity-main/src
COPY *.json /opt/neurodiversity-main/
COPY *.js /opt/neurodiversity-main/
CMD npm install && \
npm run-script build &&  \
node /opt/neurodiversity-main/src/main/server.js
EXPOSE 8080