import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/internal/Observable';
import { Resource } from './resource';

@Injectable({
  providedIn: 'root',
})
export class FirebaseService {
  constructor() {}

  public getStaticData() {
    console.log('getStaticData: ', this._staticData);
    return this._staticData;
  }

  private _staticData: Array<Resource> = [
    {
      source: 'Adweek',
      title: 'DEI Efforts Must Account for Neurodiversity',
      url: 'https://www.adweek.com/brand-marketing/dei-efforts-must-account-for-neurodiversity/',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Articles',
      tag1: 'Benefits of ND inclusion in Business',
      tag2: 'Workplace_Gen',
      tag3: 'Inclusion',
      miLevelFilters: 2,
      miAreaFilters: 'ND Inclusive hiring',
      miNotesFilters:
        'Information hihglighting the beneifits of having an ND inclusive business model',
      region: '',
      status: '',
    },
    {
      source: 'Additudemag',
      title: 'Sensory Sensitivity and ADHD',
      url: 'https://www.additudemag.com/sensory-overload-adhd-overstimulation/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Sensory Preferences',
      tag2: 'ADHD',
      tag3: 'Sensory Preferences',
      miLevelFilters: 1,
      miAreaFilters: 'Accommodating sensory preferences',
      miNotesFilters: 'Sensory overload advice',
      region: '',
      status: 1,
    },
    {
      source: 'HRReview.co.uk',
      title: 'How to make recruitment more inclusive for ADHD',
      url: 'https://www.hrreview.co.uk/analysis/katherine-kindersley-how-to-make-recruitment-more-inclusive-for-adhd/134954',
      pubYear: 2021,
      audience: 'Employers',
      categories: 'Articles',
      tag1: 'ADHD',
      tag2: 'Recruitment',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: 'Creating ND recruitment processes',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Abstract',
      title: 'Making the workplace more inclusive for Neurodiverse people',
      url: 'https://www.abstractuk.co.uk/making-the-workplace-more-inclusive-for-neurodiverse-people',
      pubYear: '',
      audience: 'Employers',
      categories: 'Articles',
      tag1: 'Opportunities',
      tag2: 'Workplace_Gen',
      tag3: 'Inclusion',
      miLevelFilters: 0,
      miAreaFilters: 'Creating strengths based development solutions',
      miNotesFilters:
        'Great info for highlighting the positives for those new to the concept of ND employability',
      region: '',
      status: 2,
    },
    {
      source: 'Unleash',
      title: 'How HR can better support neurodiverse employees',
      url: 'https://www.unleash.ai/how-hr-can-better-support-neurodiverse-employees/?utm_"source"=twitter&utm_medium=social&utm_campaign=unleash_21_07_05&utm_content=21_07_05_15_LNK',
      pubYear: 2021,
      audience: 'Employers',
      categories: 'Articles',
      tag1: 'Employability',
      tag2: 'Neurodiversity_Gen',
      tag3: 'HR',
      miLevelFilters: 1,
      miAreaFilters: 'Implementing ND specific development solutions',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'Ambitious About Autism',
      title: 'What is Autism',
      url: 'https://www.ambitiousaboutautism.org.uk/information-about-autism/understanding-autism/what-is-autism',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Autism',
      tag2: 'Basic information/Understanding',
      tag3: 'Inclusion',
      miLevelFilters: 0,
      miAreaFilters: 'ND Inclusive hiring',
      miNotesFilters:
        'Great info on how Autism affects young adults. Fantastic video interview with some young ND inviduals about their experiences and wishes.',
      region: '',
      status: 1,
    },
    {
      source: 'Neurodiversity Hub',
      title: 'How to be inclusive of autism in recruitment practices',
      url: 'https://static1.squarespace.com/static/5a88ab00f43b552a84c3b7c9/t/5d35a88154484c0001a32278/1563797640992/Neurodiversity+Hub_Inclusive+autism+recruitment+practices.pdf',
      pubYear: '',
      audience: 'Employers',
      categories: 'Articles',
      tag1: 'Autism',
      tag2: 'Recruitment',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: 'ND Inclusive hiring',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Neurodiversity Hub',
      title: 'How to successfully onboard your new autistic employee',
      url: 'https://static1.squarespace.com/static/5a88ab00f43b552a84c3b7c9/t/5d38539f129abb000103ca22/1563972517309/Neurodiversity+Hub_Inclusive+autism+Onboarding.pdf',
      pubYear: '',
      audience: 'Employers',
      categories: 'Articles',
      tag1: 'Autism',
      tag2: 'Recruitment',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: 'ND Inclusive hiring',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Dyspraxia Lambeth',
      title: 'Dyspraxia Lambeth',
      url: 'https://sites.google.com/view/dyspraxialambeth/home',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Workplace_Gen',
      tag2: 'Neurodiversity_Gen',
      tag3: 'Diagnosis',
      miLevelFilters: 0,
      miAreaFilters: 'Other',
      miNotesFilters:
        'An overview of co-habiting conditions fousing on Dyslexia, Dyspraxia',
      region: '',
      status: '',
    },
    {
      source: 'LinkedIn: Prof. Amanda Kirby',
      title: 'Neurodiversity- females, ADHD and the different paths to support',
      url: 'https://www."url"edin.com/pulse/neurodiversity-females-adhd-different-paths-support-kirby/',
      pubYear: 2022,
      audience: 'Employers',
      categories: 'Articles',
      tag1: 'Neurodiversity_Gen',
      tag2: 'ADHD',
      tag3: 'Inclusion',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Network Rail',
      title: 'Our autism friendly guide to travelling by train',
      url: 'https://www.networkrail.co.uk/wp-content/uploads/2021/09/Autism-friendly-guide-to-travelling-by-train.pdf',
      pubYear: '',
      audience: 'Employers',
      categories: 'Articles',
      tag1: 'Autism',
      tag2: 'Travel',
      tag3: 'Inclusion',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'The Times',
      title: 'Dyslexic, dyspraxic - why neurodiversity is good for business',
      url: 'https://www.thetimes.co.uk/article/dyslexic-dyspraxic-why-neurodiversity-is-good-for-business-rlwttqpq7',
      pubYear: 2020,
      audience: 'Employers',
      categories: 'Articles',
      tag1: 'Dyspraxia',
      tag2: 'Neurodiversity_Gen',
      tag3: 'Dyslexia',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'IPA',
      title: 'Neurodiversity: the hidden diversity',
      url: 'https://ipa.co.uk/knowledge/ipa-blog/neurodiversity-the-hidden-diversity',
      pubYear: 2021,
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Benefits of ND inclusion in Business',
      tag3: 'Opportunities',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Telegraph',
      title: 'What�s it really like to be autistic in the workplace?',
      url: 'https://www.telegraph.co.uk/business/autism-in-workplace/working-with-autism/',
      pubYear: 2019,
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Autism',
      tag2: 'Neurodiversity_Gen',
      tag3: 'Workplace_Gen',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Verse',
      title: 'Neurodiversity is acceptance that we are all different',
      url: 'https://www.verse.co.uk/blog/neurodiversity-is-acceptance-that-we-are-all-different',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Neurodiversity_Gen',
      tag2: 'ADHD',
      tag3: 'Inclusion',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Virgin',
      title: 'Improving the lives of adults with autism',
      url: 'https://www.virgin.com/branson-family/holly-branson-blog/improving-the-lives-of-adults-with-autism',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Autism',
      tag2: 'Neurodiversity_Gen',
      tag3: 'Adjustments',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'ADHD UK',
      title: 'What is ADHD?',
      url: 'https://adhduk.co.uk/about-adhd/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'ADHD',
      tag2: 'Diagnosis',
      tag3: 'Personal Support',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters:
        'In depth article on ADHD as a condition and how it affects indivudals medically',
      region: '',
      status: 1,
    },
    {
      source: 'Dyspraxia Lambeth',
      title: 'Dyspraxia in the workplace',
      url: 'https://sites.google.com/view/dyspraxialambeth/dyspraxia-in-the-workplace',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Dyspraxia',
      tag2: 'Workplace_Gen',
      tag3: 'Inclusion',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters:
        'A overview of Dyspraxia and how it affects individuals in the workplace and how Dyspraxic individuals can excel in the workplace',
      region: '',
      status: 1,
    },
    {
      source: 'ADHD UK',
      title: 'A workpack for ADHD individuals in the workplace',
      url: 'https://adhduk.co.uk/adhd-and-work/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'ADHD',
      tag2: 'Neurodiversity_Gen',
      tag3: 'Workplace_Gen',
      miLevelFilters: 1,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: 'Welfare pack for ADHD in the Workplace',
      region: '',
      status: 1,
    },
    {
      source: 'Genius Within',
      title: 'What is ADHD?',
      url: 'https://www.geniuswithin.org/what-is-neurodiversity/adhd/',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'ADHD',
      tag2: 'Basic information/Understanding',
      tag3: 'Personal/Familial Support suggestions',
      miLevelFilters: 1,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters:
        'A easy to digest summary of the strengths and challenges that are commonly present with ADHD',
      region: '',
      status: 2,
    },
    {
      source: 'Genius Within',
      title: 'What is Autism?',
      url: 'https://www.geniuswithin.org/what-is-neurodiversity/autism/',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Autism',
      tag2: 'Basic information/Understanding',
      tag3: 'Personal/Familial Support suggestions',
      miLevelFilters: 1,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters:
        'An overview of the strengths and challenges that are comminly associated with Autism',
      region: '',
      status: 2,
    },
    {
      source: 'Genius Within',
      title: 'What is Dyslexia?',
      url: 'https://www.geniuswithin.org/what-is-neurodiversity/dyslexia/',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Dyslexia',
      tag2: 'Basic information/Understanding',
      tag3: 'Personal/Familial Support suggestions',
      miLevelFilters: 1,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters:
        'A easy to digest summary of the strengths and challenges that are commonly present with ADHD',
      region: '',
      status: 2,
    },
    {
      source: 'Mark Charlesworth',
      title:
        'A introductory Guide to Neurodiversity for Organisations by Mark Charlesworth',
      url: 'https://neurodiversityinbusiness.sharepoint.com/:b:/s/NeurodiversityinBusiness/EdP6ME6Hwh9Crq63BW_08woBaY5sf5lNfsezxC6p9VwxsQ?e=NxOOAd',
      pubYear: 2021,
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Workplace_Gen',
      tag3: 'Inclusion',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'National Autistic Society',
      title: 'What is Autism?',
      url: 'https://www.autism.org.uk/advice-and-guidance/what-is-autism',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Autism',
      tag2: 'Neurodiversity_Gen',
      tag3: 'Inclusion',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Great Place to Work',
      title: 'How to Build and Support Neurodiversity in the Workplace',
      url: 'https://www.greatplacetowork.com/Resources/blog/how-to-build-and-support-neurodiversity-in-the-workplace',
      pubYear: 2021,
      audience: 'Employers',
      categories: 'Articles',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Workplace_Gen',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: 'Providing and supporting ND adjustments',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'Genius Within',
      title: 'What is Neurodiversity?',
      url: 'https://www.geniuswithin.org/what-is-neurodiversity/',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Inclusion',
      tag3: 'Workplace_Gen',
      miLevelFilters: 1,
      miAreaFilters: 'Providing and supporting ND adjustments',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'DI Leaders',
      title:
        'Remote & Hybrid Working Lessons for Neurodiverse Teams (by Dr Nancy Doyle)',
      url: 'https://dileaders.com/blog/remote-and-hybrid-working-lessons-for-neurodiverse-teams/',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Workplace_Gen',
      tag3: 'Adjustments',
      miLevelFilters: 1,
      miAreaFilters: 'Providing areas/solutions so ND employees can focus',
      miNotesFilters: 'Remote working techniques for a ND team/employee',
      region: '',
      status: 2,
    },
    {
      source: 'Genius Within',
      title: 'What is DCD (Dyspraxia)?',
      url: 'https://www.geniuswithin.org/what-is-neurodiversity/dcd-dyspraxia/',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Dyspraxia',
      tag2: 'Basic information/Understanding',
      tag3: 'Personal/Familial Support suggestions',
      miLevelFilters: 1,
      miAreaFilters: 'Providing areas/solutions so ND employees can focus',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'ADHD Foundation',
      title: 'Why talk about females and ADHD?" - Prof Amanda Kirby',
      url: 'https://www.adhdfoundation.org.uk/2022/03/22/why-talk-about-females-and-adhd/',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'ADHD',
      tag2: 'Research',
      tag3: 'Disability_Gen',
      miLevelFilters: 0,
      miAreaFilters: 'Understanding of organisation neurodiverse population',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'Harvard Business Review',
      title: 'Neurodiversity as a competitive advantage',
      url: 'https://hbr.org/2017/05/neurodiversity-as-a-competitive-advantage',
      pubYear: '',
      audience: 'Employers',
      categories: 'Articles',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Workplace_Gen',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: 'Understanding of organisation neurodiverse population',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'Harvard Business Review',
      title: 'Autism Doesn�t Hold People Back at Work. Discrimination Does.',
      url: 'https://hbr.org/2021/12/autism-doesnt-hold-people-back-at-work-discrimination-does',
      pubYear: 2021,
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Autism',
      tag2: 'Neurodiversity_Gen',
      tag3: 'Inclusion',
      miLevelFilters: 0,
      miAreaFilters: 'Understanding of organisation neurodiverse population',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'British Dyslexia Association',
      title: 'Dyslexia and Working from Home',
      url: 'https://cdn.bdadyslexia.org.uk/uploads/images/Dyslexia-and-Working-from-Home.pdf?v=1595254089',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Articles',
      tag1: 'Dyslexia',
      tag2: 'Workplace_Gen',
      tag3: 'Inclusion',
      miLevelFilters: 0,
      miAreaFilters: '',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'National Autistic Society',
      title: 'Employing autistic people',
      url: 'https://www.autism.org.uk/advice-and-guidance/topics/employment/employing-autistic-people/employers',
      pubYear: '',
      audience: 'Employers',
      categories: 'Articles',
      tag1: 'Autism',
      tag2: 'Hiring',
      tag3: '',
      miLevelFilters: '',
      miAreaFilters: '',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'People Management',
      title: 'Why employers should be hiring with neurodiversity in mind',
      url: 'https://www.peoplemanagement.co.uk/long-reads/articles/employers-hiring-neurodiversity#_ga=2.21034940.647295003.1635083858-2050783489.1635083858',
      pubYear: '',
      audience: 'Employers',
      categories: 'Articles',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Employer',
      tag3: '',
      miLevelFilters: '',
      miAreaFilters: '',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Shaping career choice',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/preparing-and-looking-for-work/shaping-career-choices',
      pubYear: 2021,
      audience: 'Jobseeker',
      categories: 'Articles',
      tag1: 'Careers Advice',
      tag2: 'Workplace_Gen',
      tag3: 'Employability',
      miLevelFilters: 1,
      miAreaFilters: 'Designing for Neurodivergent employees',
      miNotesFilters:
        'Grass Roots Career info and advice for Carers and Adults',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Which are your work values',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/preparing-and-looking-for-work/which-are-your-work-values',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Articles',
      tag1: 'Careers Advice',
      tag2: 'Autism',
      tag3: 'Environment',
      miLevelFilters: 1,
      miAreaFilters: 'Designing for Neurodivergent employees',
      miNotesFilters: 'Afdvice for career decsions',
      region: '',
      status: '',
    },
    {
      source: 'Google Interview Warm-up',
      title:
        'Interview practice tool. Practice answering questions by speaking or writing out your response and have AI analyze for various traits, such as mention of experience, skill',
      url: 'https://grow.google/certificates/interview-warmup/?utm_"source"=cerpar&utm_medium=cours&utm_campaign=interviewwarmup&utm_content=certshubpage',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Career Advice',
      tag1: 'Employability',
      tag2: 'Interviews',
      tag3: 'Neurodiversity_Gen',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'The National Autistic Society',
      title:
        'Finding Work: A job searching and employment preparation workbook for autistic people',
      url: 'https://s3.chorus-mk.thirdlight.com/file/1573224908/64485704518/width=-1/height=-1/format=-1/fit=scale/t=446220/e=never/k=ace51304/Finding_work_digital_workbook.pdf',
      pubYear: 2014,
      audience: 'Jobseeker',
      categories: 'Career Advice',
      tag1: 'Autism',
      tag2: 'Hiring',
      tag3: 'Employability',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Work experience',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/preparing-and-looking-for-work/work-experience',
      pubYear: '',
      audience: 'Employees',
      categories: 'Articles',
      tag1: 'Careers Advice',
      tag2: 'Employability',
      tag3: 'Internship',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: 'Advice for work experience in an ND perspective',
      region: '',
      status: '',
    },
    {
      source: 'Neurodiversity Media',
      title: '3 CAREER HACKING TIPS FOR NEURODIVERGENT PEOPLE',
      url: 'https://www.neurodiversitymedia.com/Resource-library/3-career-hacking-tips-for-neurodivergent-people',
      pubYear: 2021,
      audience: 'Employees',
      categories: 'Articles',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Employability',
      tag3: 'Personal Support',
      miLevelFilters: '',
      miAreaFilters: 'Providing ND coaching and mentoring solutions',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'JP Morgan Chase & Co.',
      title:
        'How Our Autism at Work Program Is Helping to Win the War for Top Tech Talent',
      url: 'https://www.jpmorganchase.com/news-stories/jmahoney-autism-at-work-program',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Case study',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Workplace_Gen',
      tag3: 'Autism',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Autistica',
      title:
        'Case Study: Internship Programme for Autistic Graduates at Deutsche Bank, UK',
      url: 'https://www.autistica.org.uk/downloads/files/Internship-Programe-for-Autistic-Graduates_June2017_FullReport_web.pdf',
      pubYear: 2017,
      audience: 'Everyone',
      categories: 'Case study',
      tag1: 'Internship',
      tag2: 'Autism',
      tag3: 'Benefits of ND inclusion in Business',
      miLevelFilters: 1,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters:
        'A report and case study on the beneifits that a Autisim inclusive workplace and hiring scheme produced',
      region: '',
      status: 1,
    },
    {
      source: 'WorkDesign Magazine',
      title:
        'How to design and create inclusive spaces for Neurodivergent individuals.',
      url: 'https://www.workdesign.com/2021/12/2022-workplace-trends-sensory-intelligence/?ct=t(EMAIL_CAMPAIGN_10_11_2021_COPY_01',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Research',
      tag3: 'Sensory_Sensitivity',
      miLevelFilters: 1,
      miAreaFilters: 'Accommodating sensory preferences',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'WorkDesign Magazine',
      title: 'Work Spaces: Designing For Neurodiversity And Inclusion',
      url: 'https://www.workdesign.com/2019/12/designing-for-neurodiversity-and-inclusion/',
      pubYear: 2019,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Design',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Disability Business Forum',
      title: 'Free Resource packs for disabled employees and individuals.',
      url: 'Disability Essentials - Business Disability Forum',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Disability_Gen',
      tag2: 'Legal',
      tag3: 'Disability_Law',
      miLevelFilters: 0,
      miAreaFilters: 'Accommodating sensory preferences',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'EcoPhon',
      title: 'Six design considerations for including neurodiversity',
      url: 'www.ecophon.com/exp/articles/knowledge/six-design-considerations-for-including-neurodiversity--and-much-more/?msclkid=0141c816d08f11ecaf639b83a143f460',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Design',
      tag3: 'Sensory_Sensitivity',
      miLevelFilters: 1,
      miAreaFilters: 'Accommodating sensory preferences',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Microsoft',
      title: 'Dyslexia Training In Partnership with Made By Dyslexia',
      url: 'https://docs.microsoft.com/en-us/learn/paths/dyslexia-training/',
      pubYear: '',
      audience: 'Employers',
      categories: 'Educational Resource',
      tag1: 'Dyslexia',
      tag2: 'Training',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: 'Formal Line manager training on neurodiversity',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Cognassist',
      title: 'Why is understanding Cognition important?',
      url: 'https://cognassist.com/insights/welcome-neurodiversity-101/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Personal Support',
      tag3: 'Disability_Gen',
      miLevelFilters: 0,
      miAreaFilters: 'Implementing workstyle preferences',
      miNotesFilters:
        'Overview and ground up educational Resource focusing on general cognition and how ND individuals may vary from others in their cognitive abilities',
      region: '',
      status: 1,
    },
    {
      source: 'British Dyslexia Association',
      title: 'Information anout Dyslexia',
      url: 'https://www.bdadyslexia.org.uk/dyslexia/about-dyslexia',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Dyslexia',
      tag2: 'Personal Support',
      tag3: 'Disclosure',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters:
        'General information about Dyslexia as ac condiation and how it affects individuals in their day to day lives.',
      region: '',
      status: 1,
    },
    {
      source: 'Princes Responsible Business Network',
      title: 'Supporting Neurodiversity In The Workplace',
      url: 'https://www.bitc.org.uk/wp-content/uploads/2022/07/bitc-employmentskills-factsheet-supportingneurodiversityatwork-june2022.pdf',
      pubYear: 2022,
      audience: 'Employees',
      categories: 'Educational Resource',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Workplace_Gen',
      tag3: 'Benefits of ND inclusion in Business',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Specialisterne',
      title:
        'Specialisterne Foundation works with stakeholders around the world, such as SAP, to bring about a vision of a world where people are given equal opportunities in the labor market.',
      url: 'http://specialisterne.com/',
      pubYear: '',
      audience: 'Employees',
      categories: 'Educational Resource',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Hiring',
      tag3: 'Workplace_Gen',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Neurodiversity Media',
      title: 'Blog Articles',
      url: 'https://www.neurodiversitymedia.com/Resource-library',
      pubYear: 2022,
      audience: 'Employers',
      categories: 'Educational Resource',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Workplace_Gen',
      tag3: 'Inclusion',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'HOK',
      title: 'Trends Affecting Neurodiversity Toward 2030',
      url: 'https://www.hok.com/ideas/publications/trends-affecting-neurodiversity-toward-2030/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Design',
      tag3: 'Inclusion',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Job Accomodation Network',
      title:
        'Provides practical guidance and technical assistance on job accomodation solutions',
      url: 'https://askjan.org/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Disability_Gen',
      tag2: 'Adjustments',
      tag3: 'Employability',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Mark Charlesworth',
      title: 'A Neurodiversity Guidebook by Mark Charlesworth',
      url: 'https://www.markcharlesworth.org/neurodiversityguidebook',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Neurodiversity_Gen',
      tag2: 'ADHD',
      tag3: 'Autism',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Neurodiversity Media',
      title: 'Autistic Burnout Explained: A video guide',
      url: 'https://www.neurodiversitymedia.com/autistic-burnout',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Autism',
      tag2: 'Neurodiversity_Gen',
      tag3: 'Sensory_Sensitivity',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'TextHelp',
      title: 'Understanding inclusive marketing and how you can get it right',
      url: 'https://www.texthelp.com/en-gb/Resources/digital-accessibility-guide/inclusive-marketing/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Design',
      tag3: 'Disability_Gen',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'TextHelp',
      title: 'Web Accessibility: A Digital Accessibility Guide for Marketers',
      url: 'https://www.texthelp.com/en-gb/Resources/digital-accessibility-guide/guidelines-and-legislation/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Legal',
      tag2: 'Workplace_Gen',
      tag3: 'Disability_Law',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'SFI Health',
      title:
        'Neurodiversity:  An expert opinion on a new paradigm in science and education',
      url: 'https://www.sfihealth.com/wp-content/uploads/2022/03/Neurodiversity-An-expert-opinion.pdf',
      pubYear: 2018,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Workplace_Gen',
      tag3: 'ADHD',
      miLevelFilters: 1,
      miAreaFilters: 'Providing and supporting ND adjustments',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'The Dyslexia Association',
      title: 'Dyslexia in the workplace',
      url: 'https://www.dyslexia.uk.net/employers/',
      pubYear: 2022,
      audience: 'Employees',
      categories: 'Educational Resource',
      tag1: 'Dyslexia',
      tag2: 'Diagnosis',
      tag3: 'Benefits of ND inclusion in Business',
      miLevelFilters: '',
      miAreaFilters:
        'Establishing Neurodiverse Support structures (by location)',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'National Autistic Society',
      title: 'Employing autistic people � a guide for employers',
      url: 'https://www.autism.org.uk/advice-and-guidance/topics/employment/employing-autistic-people/employers',
      pubYear: '',
      audience: 'Employees',
      categories: 'Educational Resource',
      tag1: 'Autism',
      tag2: 'Workplace_Gen',
      tag3: 'Adjustments',
      miLevelFilters: '',
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Scottish ADHD Coalition',
      title: "An employer's Guide to ADHD in the workplace",
      url: 'https://www.adhdfoundation.org.uk/wp-content/uploads/2022/03/An-Employers-Guide-to-ADHD-in-the-Workplace-Scottish-ADHD-Coalition-1.pdf',
      pubYear: 2018,
      audience: 'Employees',
      categories: 'Educational Resource',
      tag1: 'ADHD',
      tag2: 'Workplace_Gen',
      tag3: 'Neurodiversity_Gen',
      miLevelFilters: '',
      miAreaFilters: 'Providing and supporting ND adjustments',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Susan Fitzell',
      title: 'Leading Effective Team Meetings in the Neurodiverse Workplace',
      url: 'https://susanfitzell.com/leading-effective-team-meetings-in-the-neurodiverse-workplace/',
      pubYear: '',
      audience: 'Employees',
      categories: 'Educational Resource',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Workplace_Gen',
      tag3: 'Careers Advice',
      miLevelFilters: '',
      miAreaFilters: 'Providing and supporting ND adjustments',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Job Accomodation Network',
      title: 'Accommodation and Compliance: Autism Spectrum',
      url: 'https://askjan.org/disabilities/Autism-Spectrum.cfm#sq_h76l9k7w0e',
      pubYear: '',
      audience: 'Employees',
      categories: 'Educational Resource',
      tag1: 'Autism',
      tag2: 'Adjustments',
      tag3: 'Disability_Law',
      miLevelFilters: '',
      miAreaFilters: 'Understanding of organisation neurodiverse population',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'ADDA',
      title:
        'Attention Deficit Disorder Association; virtual support groups, including international',
      url: 'https://add.org/starter-kit/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'ADHD',
      tag2: 'Disability_Gen',
      tag3: 'Employability',
      miLevelFilters: 0,
      miAreaFilters: '',
      miNotesFilters:
        'A info pack fro ADHD Adults/Carers. Also great info for emploeyers and Colleuges',
      region: '',
      status: '',
    },
    {
      source: 'ADHD Foundation',
      title: 'Ten important facts about EHCPs',
      url: 'https://www.adhdfoundation.org.uk/wp-content/uploads/2022/05/10-Important-Facts-About-EHCP-Colin-Foley.pdf',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Personal Support',
      tag2: 'Disability_Gen',
      tag3: 'Diagnosis',
      miLevelFilters: 0,
      miAreaFilters: '',
      miNotesFilters:
        'Advice on what support should be available to children within the education system. Good support advice for Parent/Carer Employees',
      region: '',
      status: '',
    },
    {
      source: 'Centre for Neurodiversity at Work',
      title: 'Resources for Dyslexia At Work',
      url: '',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Dyslexia',
      tag2: 'Employability',
      tag3: 'Workplace_Gen',
      miLevelFilters: 0,
      miAreaFilters: '',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'ADHD Foundation',
      title: 'Access to work - Making work possible',
      url: 'https://www.adhdfoundation.org.uk/wp-content/uploads/2022/07/ACCESS-TO-WORK.pdf',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Adjustments',
      tag2: 'Funding Advice',
      tag3: 'HR',
      miLevelFilters: 2,
      miAreaFilters: '',
      miNotesFilters:
        'Guidance on how to access Funding through Access to Work scheme',
      region: '',
      status: '',
    },
    {
      source: 'DARE (Discover Autism Research and Employment)',
      title: 'DARE Adjustments Toolkit',
      url: 'https://dareuk.org/dare-adjustments-toolkit',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Adjustments',
      tag2: 'Workplace_Gen',
      tag3: '',
      miLevelFilters: '',
      miAreaFilters: '',
      miNotesFilters: 'NO CONTENT IS YET AVAILABLE THROUGH THIS "url"',
      region: '',
      status: '',
    },
    {
      source: 'National Autistic Society',
      title: 'The autism employment gap explained',
      url: 'https://s3.chorus-mk.thirdlight.com/file/1573224908/63516243370/width=-1/height=-1/format=-1/fit=scale/t=444848/e=never/k=59f99727/TMI%20Employment%20Report%2024pp%20WEB.pdf',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Autism',
      tag2: 'Employability',
      tag3: 'Research',
      miLevelFilters: 1,
      miAreaFilters: 'Understanding of organisation neurodiverse population',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Government',
      title: 'Outcomes for disabled people in the UK: 2021',
      url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/disability/articles/outcomesfordisabledpeopleintheuk/2021',
      pubYear: 2021,
      audience: 'Everyone',
      categories: 'Government / Law',
      tag1: 'Autism',
      tag2: 'Research',
      tag3: 'Neurodiversity_Gen',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Government',
      title:
        'National strategy for autistic children, young people and adults: 2021 to 2026',
      url: 'https://www.gov.uk/government/publications/national-strategy-for-autistic-children-young-people-and-adults-2021-to-2026',
      pubYear: 2021,
      audience: 'Everyone',
      categories: 'Government / Law',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Workplace_Gen',
      tag3: 'Autism',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Government',
      title: 'Access to Work',
      url: 'https://www.gov.uk/access-to-work',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Government / Law',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Adjustments',
      tag3: 'Disability_Law',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Sage Journals',
      title:
        'Ameliorating the disadvantage for autistic job seekers: An initial evaluation of adapted employment interview questions',
      url: 'https://journals.sagepub.com/doi/10.1177/1362361320981319',
      pubYear: 2020,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Autism',
      tag2: 'Interviews',
      tag3: 'Hiring',
      miLevelFilters: 1,
      miAreaFilters: 'Creating ND recruitment processes',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'ACAS',
      title: 'Research Paper - Neurodiversity at work',
      url: 'https://www.tourettes-action.org.uk/storage/downloads/1482243777_Neurodiversity_at_work_0916-(1).pdf',
      pubYear: 2016,
      audience: 'Employers',
      categories: 'Educational Resource',
      tag1: 'Environment',
      tag2: 'Inclusion',
      tag3: "Tourette's",
      miLevelFilters: 0,
      miAreaFilters: 'Formal Line manager training on neurodiversity',
      miNotesFilters:
        'Detailed research - 72 pgs/Detailed Approach and implementation research for ADHD/Autism/Dyslexia/Dyspraxia',
      region: '',
      status: 2,
    },
    {
      source: 'ADHD Foundation',
      title: 'ADHD in Adults',
      url: 'https://www.adhdfoundation.org.uk/wp-content/uploads/2022/03/ADHD_FOUND_Takeda_AdultsBooklet.pdf',
      pubYear: '',
      audience: 'Employees',
      categories: 'Guidebook',
      tag1: 'ADHD',
      tag2: 'Neurodiversity_Gen',
      tag3: 'Psychology',
      miLevelFilters: 0,
      miAreaFilters: '',
      miNotesFilters:
        "A comprehensive 'how to live life'  handbook compiled by a leading expert on ADHD for ADHD Adults",
      region: '',
      status: '',
    },
    {
      source: 'Rungway',
      title:
        'Your guide to embracing neurodiversity in the workplace (and being better off for it)',
      url: 'https://go.rungway.com/e-book-your-comprehensive-guide-to-neurodiversity-in-the-workplace',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Guidebook',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Workplace_Gen',
      tag3: '',
      miLevelFilters: '',
      miAreaFilters: '',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'DXC',
      title:
        'DXC Dandelion Program, successful neuroinclusivity program rolled out at DXC',
      url: 'https://dxc.com/uk/en/about-us/social-values/dxc-dandelion-program',
      pubYear: '',
      audience: 'Employers',
      categories: 'Hiring Initiative',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Hiring',
      tag3: 'Inclusion',
      miLevelFilters: '',
      miAreaFilters: 'Designing for Neurodivergent employees',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Goldman Sachs',
      title: 'Goldman Sachs Neurodiversity Hiring Initiative',
      url: 'https://www.goldmansachs.com/careers/professionals/neurodiversity-hiring-initiative.html',
      pubYear: 2022,
      audience: 'Employers',
      categories: 'Hiring Initiative',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Hiring',
      tag3: 'Neurodiversity_Gen',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Microsoft',
      title: 'Microsoft Neurodiversity Hiring Program & FAQ',
      url: 'https://www.microsoft.com/en-us/diversity/inside-microsoft/cross-disability/neurodiversityhiring',
      pubYear: '',
      audience: 'Employers',
      categories: 'Hiring Initiative',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Hiring',
      tag3: 'Recruitment',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'SAP',
      title: 'Autism at Work Program',
      url: 'https://www.sap.com/uk/about/careers/your-career/autism-at-work-program.html',
      pubYear: '',
      audience: 'Employers',
      categories: 'Hiring Initiative',
      tag1: 'Autism',
      tag2: 'Job_Application',
      tag3: 'Workplace_Gen',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'National Autistic Society',
      title: 'Autism at Work Programme',
      url: 'https://www.autism.org.uk/what-we-do/employment/autism-work-programme',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Hiring Initiative',
      tag1: 'Autism',
      tag2: 'Employability',
      tag3: 'Inclusion',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'National Autistic Society',
      title: 'Job opportunities',
      url: 'https://www.autism.org.uk/what-we-do/employment/job-opportunities',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Hiring Initiative',
      tag1: 'Autism',
      tag2: 'Job_Application',
      tag3: 'Inclusion',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Scope',
      title: 'Kickstart: employment support programme',
      url: 'https://www.scope.org.uk/employment-services/kickstart/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Hiring Initiative',
      tag1: 'Employability',
      tag2: 'Employer',
      tag3: 'Neurodiversity_Gen',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'VM Ware',
      title: 'VMWare Neurodiversity Inclusion Program',
      url: 'https://www.vmware.com/company/diversity/neurodiversity-inclusion.html',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Hiring Initiative',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Hiring',
      tag3: 'Inclusion',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Ambitious About Autism',
      title: 'Work experience opportunities',
      url: 'https://www.ambitiousaboutautism.org.uk/what-we-do/employment/paid-work-experience/work-experience-opportunities',
      pubYear: '',
      audience: 'Employers',
      categories: 'Hiring Initiative',
      tag1: 'Autism',
      tag2: 'Employability',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: '',
      miNotesFilters:
        'Helpful infomration about employment intiatives for Autism in the UK',
      region: '',
      status: '',
    },
    {
      source: 'Auticon',
      title: 'Auticon Careers',
      url: 'http://auticon.co.uk/careers/',
      pubYear: '',
      audience: 'Employers',
      categories: 'Hiring Initiative',
      tag1: 'Autism',
      tag2: 'Hiring',
      tag3: 'Employability',
      miLevelFilters: 1,
      miAreaFilters: '',
      miNotesFilters:
        'Hiring Initiative targeting Autistic Individuals for work in the IT sector',
      region: '',
      status: '',
    },
    {
      source: 'Autism Forward',
      title: 'Autism Forward Roundtable at Herbert Smith Freehills',
      url: 'http://www.autismforward.org.uk/wp-content/uploads/2019/05/Autism-Forward-Roundtable-at-HSF.pdf',
      pubYear: '',
      audience: 'Employers',
      categories: 'Hiring Initiative',
      tag1: 'Hiring',
      tag2: 'Inclusion',
      tag3: 'Interviews',
      miLevelFilters: 1,
      miAreaFilters: '',
      miNotesFilters:
        'Hiring and Job Advertisement guidance and info for employers',
      region: '',
      status: '',
    },
    {
      source: 'CAI',
      title: 'Neurodiverse Solutions',
      url: 'https://www.cai.io/neurodiverse-solutions/overview',
      pubYear: '',
      audience: 'Employees',
      categories: 'Hiring Initiative',
      tag1: 'Interviews',
      tag2: 'Inclusion',
      tag3: 'Employability',
      miLevelFilters: 2,
      miAreaFilters: '',
      miNotesFilters:
        'Infgormation about CAI, a fantastic ND employment designed to support individuals on their path to employment',
      region: 'US',
      status: '',
    },
    {
      source: 'Lime Connect',
      title:
        'Lime Connect represents largest network of high-potential university students and professionals - including veterans - who have disabilities in the world',
      url: 'https://www.limeconnect.com/#who-we-are',
      pubYear: '',
      audience: 'Employers',
      categories: 'Job Board',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Hiring',
      tag3: 'Internship',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Microsoft',
      title: 'Neurodiversity Career Connector',
      url: 'https://ndcc.simplifyhire.com/',
      pubYear: '',
      audience: 'Employers',
      categories: 'Job Board',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Hiring',
      tag3: 'Recruitment',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Mary Ann Liebert, Inc., publishers',
      title:
        'Workbased Disclosure Experiences of Autistic Individuals in the Workplace',
      url: 'https://www.liebertpub.com/doi/full/10.1089/aut.2020.0063',
      pubYear: 2021,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Autism',
      tag2: 'Diagnosis',
      tag3: 'Disclosure',
      miLevelFilters: 1,
      miAreaFilters: 'Providing and supporting ND adjustments',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'British Dyslexia Association',
      title: 'How can I support my dyslexic employees?',
      url: 'https://www.bdadyslexia.org.uk/advice/employers/how-can-i-support-my-dyslexic-employees',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Law and regulation',
      tag1: 'Dyslexia',
      tag2: 'Disability_Law',
      tag3: 'HR',
      miLevelFilters: 0,
      miAreaFilters: 'Providing and supporting ND adjustments',
      miNotesFilters:
        'Manager specific advice and information regarding supporting a Dyslexic Employee and related legislation',
      region: '',
      status: '',
    },
    {
      source: 'British Dyslexia Association',
      title: 'How can I support my dyslexic employees',
      url: 'https://www.bdadyslexia.org.uk/advice/employers/how-can-i-support-my-dyslexic-employees',
      pubYear: '',
      audience: 'Employers',
      categories: 'Law and regulation',
      tag1: 'Dyslexia',
      tag2: 'HR',
      tag3: 'Legal',
      miLevelFilters: 1,
      miAreaFilters: '',
      miNotesFilters:
        'Great and concise info on the responsibilites of employers when managing Dyslexic Employees',
      region: '',
      status: '',
    },
    {
      source: 'Inclusiveemployers.co.uk',
      title: 'What is Inclusion?',
      url: 'https://www.inclusiveemployers.co.uk',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Organization',
      tag1: 'Inclusion',
      tag2: 'Neurodiversity_Gen',
      tag3: 'Training',
      miLevelFilters: '',
      miAreaFilters: 'Formal Line manager training on neurodiversity',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Diverse Sussex',
      title:
        'Aligning our common goal of ensuring everyone has equal access to opportunities in Sussex�s technology sector.',
      url: 'https://diversesussex.com/',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Organization',
      tag1: 'Inclusion',
      tag2: 'Workplace_Gen',
      tag3: 'Workplace_Gen',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Ambitious About Autism',
      title: 'Employ Autism',
      url: 'https://www.ambitiousaboutautism.org.uk/what-we-do/employment/employers',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Organization',
      tag1: 'Training',
      tag2: 'Autism',
      tag3: 'Hiring',
      miLevelFilters: 2,
      miAreaFilters: '',
      miNotesFilters:
        'Information on Autism training programmes for managers and leaders within companies',
      region: '',
      status: '',
    },
    {
      source: 'Dyspraxia Foundation',
      title: 'Dyspraxia Foundation',
      url: 'https://dyspraxiafoundation.org.uk',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Organization',
      tag1: 'Dyspraxia',
      tag2: 'Neurodiversity_Gen',
      tag3: '',
      miLevelFilters: '',
      miAreaFilters: '',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Autism Spectrum News',
      title: 'Global Study on Employing Autistic Adults',
      url: 'https://www.autismspectrumnews.org/autism-work-insights-from-a-world-first-global-study-on-employing-autistic-adults/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Report',
      tag1: 'Research',
      tag2: 'Emotional_Sensitivity',
      tag3: 'Environment',
      miLevelFilters: 2,
      miAreaFilters: '',
      miNotesFilters:
        'Reported findings into what really affected  ND individuals within the workplace from a academic perspective',
      region: '',
      status: '',
    },
    {
      source: 'Sage Journals',
      title:
        'Autistic adults� experiences of diagnostic disclosure in the workplace',
      url: 'https://journals.sagepub.com/doi/full/10.1177/23969415211022955',
      pubYear: 2021,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Autism',
      tag2: 'Psychological_Safety',
      tag3: 'Research',
      miLevelFilters: 0,
      miAreaFilters: 'Understanding of organisation neurodiverse population',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'Sage Journals',
      title:
        'Experiences of autistic and non-autistic individuals participating in a corporate internship scheme',
      url: 'https://journals.sagepub.com/doi/full/10.1177/13623613211025115',
      pubYear: 2021,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Autism',
      tag2: 'Internship',
      tag3: 'Research',
      miLevelFilters: 1,
      miAreaFilters: 'Understanding of organisation neurodiverse population',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'Ability Net',
      title: 'What Are Reasonable Adjustments?',
      url: 'https://abilitynet.org.uk/workplace/what-are-reasonable-adjustments?gclid=EAIaIQobChMI7-HAk5u1-QIVR_hRCh1_Iw5EEAAYASAAEgI9OvD_BwE',
      pubYear: 2010,
      audience: 'Everyone',
      categories: 'Government / Law',
      tag1: 'Adjustments',
      tag2: 'Workplace_Gen',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: 'Formal Line manager training on neurodiversity',
      miNotesFilters:
        'Good for employerss who are looking to understand the legal responsibilities of employers more clearly',
      region: '',
      status: 1,
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Current research projects',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/our-research/current-research-projects',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Research',
      tag1: 'Research',
      tag2: 'Autism',
      tag3: 'Environment',
      miLevelFilters: 2,
      miAreaFilters: 'Other',
      miNotesFilters:
        'Research page - looking for volunteers to participate in research (limited use?)',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Participate in our research',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/our-research/participate-in-our-research',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Research',
      tag1: 'Autism',
      tag2: 'Research',
      tag3: 'Opportunities',
      miLevelFilters: 2,
      miAreaFilters: 'Other',
      miNotesFilters: 'Research Opportunity',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Past research projects',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/our-research/past-research-projects',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Research',
      tag1: 'Autism',
      tag2: 'Research',
      tag3: 'Neurodiversity_Gen',
      miLevelFilters: 2,
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'The Westminster AchieveAbility Commission',
      title: 'Neurodiverse voices: Opening Doors to Employment',
      url: 'https://www.achieveability.org.uk/files/1516612947/wac-neurodiverse-voices-opening-doors-to-employment-report_2018_interactive.pdf',
      pubYear: 2018,
      audience: 'Everyone',
      categories: 'Research',
      tag1: 'Employability',
      tag2: 'Neurodiversity_Gen',
      tag3: 'Hiring',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'British Dyslexia Association',
      title: 'Autsitic Employee rights advice for the workplace',
      url: 'https://www.bdadyslexia.org.uk/advice/adults/in-the-workplace',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Law and regulation',
      tag1: 'Dyslexia',
      tag2: 'Disability_Law',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters:
        'Concise information about employees rights in the workplace in realtion to Dyslexia',
      region: '',
      status: 1,
    },
    {
      source: 'Neurodiversity Hub',
      title: 'A workbook for autistic jobseekers',
      url: 'https://static1.squarespace.com/static/5a88ab00f43b552a84c3b7c9/t/613318c90ba34b71efe58543/1630738642357/Job+Readiness+Workbook-editable-July_2021.pdf',
      pubYear: 2021,
      audience: 'Employers',
      categories: 'Toolkits and handbooks',
      tag1: 'Autism',
      tag2: 'Job_Application',
      tag3: 'Employability',
      miLevelFilters: 1,
      miAreaFilters: 'Providing ND coaching and mentoring solutions',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Mark Charlesworth',
      title: 'The Eleven Principles Of Neurodiversity Inclusion',
      url: 'https://www.markcharlesworth.org/eleven',
      pubYear: 2022,
      audience: 'Everyone',
      categories: 'Toolkits and handbooks',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Inclusion',
      tag3: 'Adjustments',
      miLevelFilters: 1,
      miAreaFilters: 'Understanding of organisation neurodiverse population',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'DARE (Discover Autism Research and Employment)',
      title: 'Diverse Minds Employment Survey',
      url: 'https://uclioe.eu.qualtrics.com/jfe/form/SV_dhVjxZbHpkPdiIu',
      pubYear: '',
      audience: 'Employers',
      categories: 'Research',
      tag1: 'Inclusion',
      tag2: 'Neurodiversity_Gen',
      tag3: '',
      miLevelFilters: '',
      miAreaFilters: '',
      miNotesFilters: '"url" IS DEAD!!',
      region: '',
      status: '',
    },
    {
      source: 'TextHelp',
      title: 'Guides, eBooks, podcasts, templates and more to help you grow',
      url: 'https://www.texthelp.com/en-gb/Resources/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Resources',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Personal Support',
      tag3: 'Opportunities',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Autism Forward',
      title: 'Autism Forward Roundtable at Latham and Watkins',
      url: 'http://www.autismforward.org.uk/wp-content/uploads/2019/07/Autism-Forward-Recruitment-Roundtable-at-LW.pdf',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Roundtable',
      tag1: 'Hiring',
      tag2: 'Inclusion',
      tag3: 'Interviews',
      miLevelFilters: 1,
      miAreaFilters: '',
      miNotesFilters: 'Overview of the Success of Autism hiring initiatives',
      region: '',
      status: '',
    },
    {
      source: 'Autism Forward',
      title: 'Autism Forward Roundtable at Credit Suisse',
      url: 'http://www.autismforward.org.uk/wp-content/uploads/2019/10/Credit-Suisse_Autism-Forward-Roundtable-Notes.pdf',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Roundtable',
      tag1: 'Autism',
      tag2: 'Benefits of ND inclusion in Business',
      tag3: 'Round_Table',
      miLevelFilters: 2,
      miAreaFilters: '',
      miNotesFilters:
        'Report on a roundtable discussion highlighting the benefits of ND friendly interview techniques and recrutiment drives',
      region: '',
      status: '',
    },
    {
      source: 'National Autistic Society',
      title: 'Employing autistic people � a guide for employers',
      url: 'https://www.autism.org.uk/advice-and-guidance/topics/employment/employing-autistic-people/employers',
      pubYear: '',
      audience: 'Employers',
      categories: 'Toolkits and handbooks',
      tag1: 'Autism',
      tag2: 'Employer',
      tag3: 'Hiring',
      miLevelFilters: 1,
      miAreaFilters: 'Creating ND job and role descriptions',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Aybe',
      title: 'Join our community for neurodiverse families',
      url: 'http://www.aybeapp.com/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkits and handbooks',
      tag1: 'Support Groups',
      tag2: 'Personal Support',
      tag3: 'Opportunities',
      miLevelFilters: 1,
      miAreaFilters: 'Formal Line manager training on neurodiversity',
      miNotesFilters:
        'A collection of information about family support services for families with ND members. Great for employee support for parents and carers od ND family members',
      region: '',
      status: 1,
    },
    {
      source: 'Shire',
      title: 'Understanding ADHD in adults',
      url: 'https://www.adhdfoundation.org.uk/wp-content/uploads/2019/01/Understanding-ADHD-in-Adults_FINAL.pdf',
      pubYear: '',
      audience: 'Employers',
      categories: 'Toolkit',
      tag1: 'ADHD',
      tag2: 'Neurodiversity_Gen',
      tag3: '',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'The Law Society',
      title:
        'Reasonable adjustments in organisations � best practice for disability inclusion',
      url: 'https://www.lawsociety.org.uk/topics/lawyers-with-disabilities/reasonable-adjustments-in-organisations-best-practice-for-disability-inclusion',
      pubYear: 2021,
      audience: 'Employers',
      categories: 'Toolkit',
      tag1: 'Disability_Law',
      tag2: 'Adjustments',
      tag3: 'Inclusion',
      miLevelFilters: '',
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Beyond Autism',
      title: 'Employability Toolkit for Autistic Individuals',
      url: 'https://neurodiversityinbusiness.sharepoint.com/:b:/s/NeurodiversityinBusiness/EZNS0ME_aq5Jixr4HQ9sLpcB7dZuop6_wKXRJEWGLrNWMw?e=MFmEiJ',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkits and handbooks',
      tag1: 'Autism',
      tag2: 'Employability',
      tag3: 'Benefits of ND inclusion in Business',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: 'An Overview of Autisitc Hiring and emplymnet practices',
      region: '',
      status: 2,
    },
    {
      source: 'Erasmus+ Programme of the European Union',
      title:
        'Training curricula for people starting work with adult people with autism',
      url: 'https://asmentoring.co.uk/wp-content/uploads/2018/10/ASM-section-EU-Project-Handbook-2018.pdf',
      pubYear: 2018,
      audience: 'Employers',
      categories: 'Toolkits and handbooks',
      tag1: 'Autism',
      tag2: 'Employer',
      tag3: 'Training',
      miLevelFilters: 1,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'Mental Health at Work',
      title: 'Making your workplace more autistic-friendly',
      url: 'https://www.mentalhealthatwork.org.uk/toolkit/making-your-workplace-more-autistic-friendly/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkits and handbooks',
      tag1: 'Autism',
      tag2: 'Adjustments',
      tag3: 'Neurodiversity_Gen',
      miLevelFilters: 1,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: 2,
    },
    {
      source: 'Beyond Autism',
      title: 'Employability Toolkit - Workpacks for Autism in the Worrkplace',
      url: 'https://neurodiversityinbusiness.sharepoint.com/:b:/s/NeurodiversityinBusiness/Ef5zE-7FLrhIsfaUM20GKBYBplLLLV502FET4lrYeUvo5A?e=gKXkj0',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkits and handbooks',
      tag1: 'Autism',
      tag2: 'Design',
      tag3: 'Management',
      miLevelFilters: 0,
      miAreaFilters: 'Providing and supporting ND adjustments',
      miNotesFilters:
        'Resource Pack for inclusion strategies and techiniques for managing ASD employees',
      region: '',
      status: 1,
    },
    {
      source: 'TextHelp',
      title:
        'Powerful reading and writing tools to help neurodiverse workforces to thrive.',
      url: 'https://www.texthelp.com/products/read-and-write-workplace/neurodiversity/?utm_content=Inclusive+tech+empowers+success+for+ALL&utm_medium=Email&utm_"source"=Mautic&utm_campaign=Private-Sector%7CGL-WP-RW-Nurture-ENG-2021-2022',
      pubYear: '',
      audience: 'Employers',
      categories: 'Toolkits and handbooks',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Workplace_Gen',
      tag3: 'Adjustments',
      miLevelFilters: 1,
      miAreaFilters: 'Providing assistive technologies/tools for ND employees',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Disability Business Forum',
      title: "A 'Disability Smart' Toolkit",
      url: 'https://businessdisabilityforum.org.uk/disability-smart-suite/ds-toolkit/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkits and handbooks',
      tag1: 'Disability_Gen',
      tag2: 'Adjustments',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: 'Providing assistive technologies/tools for ND employees',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Universal Music',
      title:
        'Creative Differences: Embracing Neurodiversity in the creative industries',
      url: 'https://umusic.co.uk/Creative-Differences-Handbook.pdf',
      pubYear: '',
      audience: 'Employers',
      categories: 'Toolkits and handbooks',
      tag1: 'Neurodiversity_Gen',
      tag2: 'Inclusion',
      tag3: 'Benefits of ND inclusion in Business',
      miLevelFilters: 1,
      miAreaFilters: 'Understanding of organisation neurodiverse population',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Dublin City University in partnership with Indeed',
      title: 'Hiring Managers� Toolkit for Neurodiversity',
      url: 'https://static1.squarespace.com/static/5a88ab00f43b552a84c3b7c9/t/5f4081b20502cb348f88df0a/1598063085626/managers_toolkit_.pdf',
      pubYear: 2020,
      audience: 'Employees',
      categories: 'Toolkits and handbooks',
      tag1: 'Dyslexia',
      tag2: 'Employer',
      tag3: 'Hiring',
      miLevelFilters: '',
      miAreaFilters: 'ND Inclusive hiring',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Managing conflict',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/at-work/managing-conflict',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkit',
      tag1: 'Autism',
      tag2: 'Senory_Sensitivity',
      tag3: 'Pyschological_Sensitivity',
      miLevelFilters: 0,
      miAreaFilters: '',
      miNotesFilters:
        'Illustrates the challenges from interpersonal conflict that an individual with Autism can face in an education setting (Transferable to workplace however)',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Telling people about your autism',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/at-work/telling-people-about-your-autism',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Toolkit',
      tag1: 'Disclosure',
      tag2: 'HR',
      tag3: 'Autism',
      miLevelFilters: 0,
      miAreaFilters: '',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'When to disclose?',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/preparing-and-looking-for-work/to-disclose-or-not-to-disclose',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Toolkit',
      tag1: 'Autism',
      tag2: 'Disclosure',
      tag3: 'Inclusion',
      miLevelFilters: 0,
      miAreaFilters: '',
      miNotesFilters: 'Employee disclosure advice',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Preparing and looking for work',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/preparing-and-looking-for-work',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Toolkit',
      tag1: 'Employability',
      tag2: 'Autism',
      tag3: 'Hiring',
      miLevelFilters: 0,
      miAreaFilters: '',
      miNotesFilters:
        'Startegies for ND jobseekers. Focuse on Autism but can be applied for multiple individuals',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Meeting people at work',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/at-work/meeting-people-at-work',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Toolkit',
      tag1: 'Autism',
      tag2: 'Workplace_Gen',
      tag3: 'Environment',
      miLevelFilters: 0,
      miAreaFilters: '',
      miNotesFilters:
        'Advice and Guidance on how to interact with Colleagues. Fantastic insight into the challenges that Autism can bring in Social Situations',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'At work',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/at-work',
      pubYear: '',
      audience: 'Employers',
      categories: 'Toolkit',
      tag1: 'Workplace_Gen',
      tag2: 'Disclosure',
      tag3: 'Disability Gen',
      miLevelFilters: 1,
      miAreaFilters: '',
      miNotesFilters:
        'General advice for employers and employees about Disclosure and how to approach workplace situations from an ND perspective',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Applying for jobs',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/preparing-and-looking-for-work/applying-for-jobs',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkit',
      tag1: 'Employability',
      tag2: 'Job Application',
      tag3: 'Autism',
      miLevelFilters: 1,
      miAreaFilters: '',
      miNotesFilters: 'Application Advice and Guidance for ND applicants',
      region: '',
      status: '',
    },
    {
      source: 'ADHD UK',
      title: '2021 ADHD Welfare Pack',
      url: 'https://adhduk.co.uk/adhd-and-work/',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkit',
      tag1: 'ADHD',
      tag2: 'Neurodiversity_Gen',
      tag3: 'Workplace_Gen',
      miLevelFilters: 1,
      miAreaFilters: '',
      miNotesFilters: 'Welfare pack',
      region: '',
      status: '',
    },
    {
      source: 'Autism Forward',
      title: 'Autism Forward Roundtable at River and Mercantile',
      url: 'http://www.autismforward.org.uk/wp-content/uploads/2020/01/Autism-Forward-Recruitment-Roundtable-at-RM-1.pdf',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkit',
      tag1: 'Management',
      tag2: 'Training',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: '',
      miNotesFilters:
        'Report on the efficacy of inclusive hiring and promotional practices within a corporate organisation. Includes ND skill assessor for Employers and Employees to use to identify key strengths in individuals',
      region: '',
      status: '',
    },
    {
      source: 'Autism Forward',
      title: 'Autism Forward Roundtable with Adjust Services',
      url: 'http://www.autismforward.org.uk/wp-content/uploads/2020/06/Autism-Forward-Recruitment-Roundtable-with-Adjust-Services.pdf',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkit',
      tag1: 'Autism',
      tag2: 'Environment',
      tag3: 'Inclusion',
      miLevelFilters: 1,
      miAreaFilters: '',
      miNotesFilters:
        'Strategies and guidance from emplyers and Managers on how to be inclusive to Autistic Individuals and create inclusive environments',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Arranging reasonable adjustments',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/at-work/arranging-reasonable-adjustments',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkit',
      tag1: 'HR',
      tag2: 'Adjustments',
      tag3: 'Disclosure',
      miLevelFilters: 2,
      miAreaFilters: '',
      miNotesFilters:
        'Advanced Adjustment Guidance for Employees and Employers',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Wellbeing',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/at-work/wellbeing',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkit',
      tag1: 'Autism',
      tag2: 'Sensory_Sensitivity',
      tag3: 'Employability',
      miLevelFilters: 2,
      miAreaFilters: '',
      miNotesFilters:
        'Practical Tips and Guidance for Sensory Sensitive Employees on how to minimise stress in the workplace',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: "Disclosing your diagnosis: The employee's view",
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/at-work/the-employees-view-on-disclosing-diagnosis',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Toolkit',
      tag1: 'Autism',
      tag2: 'Diagnosis',
      tag3: 'Disclosure',
      miLevelFilters: 2,
      miAreaFilters: '',
      miNotesFilters:
        'Good Resource for Employers and Employees to learn about some of more specific challenges and experiences of ND disclosure from the perspective of employees',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Access to Work support',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/at-work/access-to-work-support',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Toolkit',
      tag1: 'HR',
      tag2: 'Adjustments',
      tag3: 'Environment',
      miLevelFilters: 2,
      miAreaFilters: '',
      miNotesFilters: 'How to Access Gov funding for Adjustments',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Identifying strengths',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/preparing-and-looking-for-work/identifying-strengths-preferences-and-training-needs',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Toolkit',
      tag1: 'Hiring',
      tag2: 'Management',
      tag3: 'Inclusion',
      miLevelFilters: 2,
      miAreaFilters: '',
      miNotesFilters:
        'Guidance on Task allocation strategies for ND individuals',
      region: '',
      status: '',
    },
    {
      source: 'ACRE (Autism Centre for Research on Employment)',
      title: 'Autism Employment Toolkit',
      url: 'https://sites.google.com/port.ac.uk/autismemploymenttoolkit/employment-toolkit',
      pubYear: '',
      audience: 'Jobseeker',
      categories: 'Toolkit',
      tag1: 'Hiring',
      tag2: 'Employability',
      tag3: 'Opportunities',
      miLevelFilters: 2,
      miAreaFilters: '',
      miNotesFilters:
        'Specific Guidance for Job seekers and prospective students with ND traits',
      region: '',
      status: '',
    },
    {
      source:
        'EY, Microsoft, JP Morgan, SAP, Information School - University of Washington',
      title: 'Autism @ Work Playbook',
      url: 'https://s3.amazonaws.com/disabilityin-bulk/2019/Autism_At_Work_Playbook_Final_02112019.pdf',
      pubYear: '',
      audience: 'Employers',
      categories: 'Toolkit',
      tag1: 'Autism',
      tag2: 'Workplace_Gen',
      tag3: '',
      miLevelFilters: '',
      miAreaFilters: '',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Foundation for People with Learning Disabilities',
      title: 'Autism, Aspergers, employment and mental health',
      url: 'https://www.mentalhealth.org.uk/sites/default/files/ASD_Employment__Mental_Health.pdf',
      pubYear: '',
      audience: 'Employers',
      categories: 'Toolkit',
      tag1: 'Autism',
      tag2: 'Employability',
      tag3: '',
      miLevelFilters: '',
      miAreaFilters: '',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Data & Marketing Association',
      title: 'Autism Employer Guide',
      url: 'https://dma.org.uk/uploads/misc/dma-talent-autism-employer-guide-final.pdf',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Toolkit',
      tag1: 'Autism',
      tag2: 'Employability',
      tag3: '',
      miLevelFilters: '',
      miAreaFilters: '',
      miNotesFilters: 'NOT A "url", AND PDF "url" DOERS NOT WORK',
      region: '',
      status: '',
    },
    {
      source: 'Deloitte',
      title: "Deloitte's Neurodiversity Learning Guide",
      url: 'https://www2.deloitte.com/uk/en/pages/neurodiversity-learning-guides.html',
      pubYear: 2022,
      audience: 'Employers',
      categories: 'Toolkits and handbooks',
      tag1: 'Management',
      tag2: 'Design',
      tag3: 'Recruitment',
      miLevelFilters: 1,
      miAreaFilters: 'Methods for accessing ND talent',
      miNotesFilters:
        'Training guide for managers on how to undertsand and manage ND traits and individuals',
      region: '',
      status: 1,
    },
    {
      source: 'Autistica',
      title:
        'Autistica Support Plan � How to build a proven support system for autistic people by 2030',
      url: 'https://neurodiversityinbusiness.org/wp-content/uploads/2022/11/Autistica-Support-Plan.pdf',
      pubYear: 2021,
      audience: 'Everyone',
      categories: 'Toolkits and handbooks',
      tag1: 'Autism',
      tag2: 'Research',
      tag3: 'Personal/Familial Support suggestions',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Cognassist',
      title: '10 workplace adjustments to support neurodiversity',
      url: 'https://cognassist.com/insights/10-workplace-adjustments-to-support-neurodiversity',
      pubYear: 2023,
      audience: 'Everyone',
      categories: 'Toolkits and handbooks',
      tag1: 'Adjustments',
      tag2: 'Inclusion',
      tag3: 'Support',
      miLevelFilters: 0,
      miAreaFilters: 'Providing and supporting ND adjustments',
      miNotesFilters: '',
      region: '',
      status: 1,
    },
    {
      source: 'Cognassist',
      title:
        'Employers� Responsibilities: Reasonable Adjustments, Equality Act & Discrimination',
      url: 'https://cognassist.com/insights/reasonable-adjustments-equality-act/',
      pubYear: 2023,
      audience: 'Employers',
      categories: 'Law and regulation',
      tag1: 'Law',
      tag2: 'Adjustments',
      tag3: 'Inclusion',
      miLevelFilters: 0,
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Cognassist',
      title: '8 cognitive strategies to enhance retention and learning',
      url: 'https://cognassist.com/insights/cognitive-strategies/',
      pubYear: 2023,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Adjustments',
      tag2: 'Inclusion',
      tag3: 'Support',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Cognassist',
      title: 'Building an inclusive learning culture at work',
      url: 'https://cognassist.com/insights/3-steps-for-building-a-culture-of-learning-at-work/',
      pubYear: 2023,
      audience: 'Everyone',
      categories: 'Toolkits and handbooks',
      tag1: 'Awareness',
      tag2: 'Inclusion',
      tag3: 'Support',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Cognassist',
      title:
        'Great minds don�t think alike: Tips for a neuro-inclusive workplace',
      url: 'https://cognassist.com/insights/tips-for-a-neuro-inclusive-workplace/',
      pubYear: 2023,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Adjustments',
      tag2: 'Inclusion',
      tag3: 'Support',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Cognassist',
      title: '4 crucial steps to support and manage neurodiverse employees',
      url: 'https://cognassist.com/insights/manage-neurodiverse-employees/',
      pubYear: 2023,
      audience: 'Everyone',
      categories: 'Toolkits and handbooks',
      tag1: 'Adjustments',
      tag2: 'Inclusion',
      tag3: 'Support',
      miLevelFilters: 0,
      miAreaFilters: 'Formal Line manager training on neurodiversity',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Cognassist',
      title: 'Top tips for raising neurodiversity awareness in your workplace',
      url: 'https://cognassist.com/insights/raising-neurodiversity-awareness-in-your-workplace/',
      pubYear: 2023,
      audience: 'Everyone',
      categories: 'Toolkits and handbooks',
      tag1: 'Awareness',
      tag2: 'Inclusion',
      tag3: 'Support',
      miLevelFilters: 0,
      miAreaFilters: 'Other',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Cognassist',
      title:
        'Neurodiversity recruitment: How neuro-inclusive are your hiring practices?',
      url: 'https://cognassist.com/insights/neurodiversity-recruitment/',
      pubYear: 2023,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Processes',
      tag2: 'Hiring',
      tag3: 'Adjustments',
      miLevelFilters: 0,
      miAreaFilters: 'Creating ND recruitment processes',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Cognassist',
      title:
        'Common barriers to equality, diversity and inclusion initiatives and how to overcome them',
      url: 'https://cognassist.com/insights/common-barriers-to-equality-diversity-and-inclusion/',
      pubYear: 2023,
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: 'Awareness',
      tag2: 'Inclusion',
      tag3: 'Adjustments',
      miLevelFilters: 0,
      miAreaFilters: 'Provide Neurodiversity learning materials to employees',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Cognassist',
      title:
        'Your quick guide to equality, diversity, and inclusion in the workplace',
      url: 'https://cognassist.com/insights/equality-diversity-and-inclusion-in-the-workplace/',
      pubYear: 2023,
      audience: 'Everyone',
      categories: 'Toolkits and handbooks',
      tag1: 'Processes',
      tag2: 'Law',
      tag3: 'Inclusion',
      miLevelFilters: 0,
      miAreaFilters: 'Understanding of organisation neurodiverse population',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Cognassist',
      title: 'Neurodiverse Life 3-part podcast series with guest speakers',
      url: 'https://gbr01.safe"url"s.protection.outlook.com/?url=https%3A%2F%2Fcognassist.com%2Fpodcasts%2Fneurodiverse-life%2F&data=05%7C01%7Cgeorginakennedy%40cognassist.com%7C09762aec8adc4b1e092508dadd348cb4%7C3edc4486587846a9a9742a7787926f35%7C1%7C0%7C638065515007869856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PF7eCz%2FGmmKmHA3vta6%2F4O8KjP9xVd%2FqBZY3YBjw0pk%3D&reserved=0',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource',
      tag1: '',
      tag2: '',
      tag3: '',
      miLevelFilters: '',
      miAreaFilters: '',
      miNotesFilters: '',
      region: '',
      status: '',
    },
    {
      source: 'Cognassist',
      title:
        'Episode two features Theo Smith talking about Neurodiversity at Work',
      url: 'https://cognassist.com/podcasts/neurodiverse-life/?wchannelid=pxqymltumi&wmediaid=u3ls1ak34r',
      pubYear: '',
      audience: 'Everyone',
      categories: 'Educational Resource"',
      tag1: '',
      tag2: '',
      tag3: '',
      miLevelFilters: '',
      miAreaFilters: '',
      miNotesFilters: '',
      region: '',
      status: '',
    },
  ];
}
