name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
    - name: Install the packages
      run: cd ../ && npm install
    - uses: actions/setup-node@v3
    - name: Run Angular Production Build
      run: npm run-script build
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
