name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Angular CLI
      run: |
        npm install -g @angular/cli
        npm install
        npm run-script build
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
