name: Create Archive
on:
  push:
    branches: [ "feature/*" ]
permissions:
    contents: write  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
    - name: Test with environment variables
      run: echo $TAG_NAME - $RELEASE_NAME
      env:
        TAG_NAME: ${{ steps.extract_branch.outputs.branch }}-${{ steps.date.outputs.date }}
        RELEASE_NAME: Build ${{ steps.extract_branch.outputs.branch }}-${{ steps.date.outputs.date }}
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run-script converage
    - name: Produce Coverage Report
    - name: Code Coverage Report
    - uses: actions/upload-artifact@v3
      with:
        name: Coverage Report
        path: coverage/neurodiversity-main
