# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Build and Unit Tests

on:
  push:
    branches: ["development"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Build Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      - uses: actions/checkout@v3
      - name: Build Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm run-script coverage
      - uses: actions/upload-artifact@v3
        with:
          name: Coverage Report
          path: coverage/neurodiversity-main/
      - uses: actions/download-artifact@master
        with:
          name: Coverage Report
          path: .
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    name: Test
    needs: build
    steps:
      - uses: actions/setup-node@v3
      - run: npm test
  archive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    name: Archive
    needs: test
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: nib-static-site
          path: |
            public/neurodiversity-main/
  create-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    name: Create Release
    needs: test
    steps:
      - uses: ncipollo/release-action@v1
        with:
          tag: "nightly-tag-${{ steps.date.outputs.date }}"
          artifacts: "release.zip"
          prerelease: true
