name: Create Archive
on:
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "development" , "master"]
permissions:
    contents: write  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Test with environment variables
      run: echo $TAG_NAME - $RELEASE_NAME
      env:
        TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
        RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
    - name: Checkout
      uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1 
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* .vscode* .editorconfig'
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        draft: false
        prerelease: true
        commitish: true
