name: Create Archive
on:
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "development" , "master"]
permissions:
    contents: write  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1 
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* .vscode* .editorconfig'
    - name: Set new tag
      id: newtag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag=$(gh release view --json tagName --jq '.tagName')
        IFS=. read -r major minor patch <<< "$tag"
        echo "newtag=$major.$minor.$((++patch))" >> "$GITHUB_OUTPUT"

    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        tag: ${{ steps.newtag.outputs.newtag }}
        replacesArtifacts: false
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
