name: Create Archive
on:
  push:
    branches: [ "staging", "production" ]
  pull_request:
    branches: [  "staging" , "production"]
permissions:
    contents: write  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
    - name: Test with environment variables
      run: echo $TAG_NAME - $RELEASE_NAME
      env:
        TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
        RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1 
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* .vscode* .editorconfig'
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-tag-${{ steps.date.outputs.date }}
        release_name:  nightly-release-${{ steps.date.outputs.date }}
        draft: false
        prerelease: true
    - uses: ncipollo/release-action@v1
      with:
        tag: "nightly-tag-${{ steps.date.outputs.date }}"
        artifacts: "release.zip"
