name: Create Archive
on:
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "development" , "master"]
permissions:
    contents: write  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1 
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* .vscode* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with: 
        artifacts: "release.zip"
        tag: true
        commit: true
